// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhgZrMzn8dfLPb3NoB85SuPII-VxteGKw',
    appId: '1:163933915965:web:79a5b5ed1bc40e7ce85354',
    messagingSenderId: '163933915965',
    projectId: 'attendance-tracking-f54d9',
    authDomain: 'attendance-tracking-f54d9.firebaseapp.com',
    storageBucket: 'attendance-tracking-f54d9.appspot.com',
    measurementId: 'G-XSNZPMB8XN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJFLf-ls-p48p-_kYopVQd_0q22dbSjmE',
    appId: '1:163933915965:android:faf4b13e9e2775cbe85354',
    messagingSenderId: '163933915965',
    projectId: 'attendance-tracking-f54d9',
    storageBucket: 'attendance-tracking-f54d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH3OKek-oocEuOdU728TlY9oDItpqrG3Y',
    appId: '1:163933915965:ios:7f01e0dbc7709665e85354',
    messagingSenderId: '163933915965',
    projectId: 'attendance-tracking-f54d9',
    storageBucket: 'attendance-tracking-f54d9.appspot.com',
    iosBundleId: 'com.example.attendenceTracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH3OKek-oocEuOdU728TlY9oDItpqrG3Y',
    appId: '1:163933915965:ios:1d05186a17d8f314e85354',
    messagingSenderId: '163933915965',
    projectId: 'attendance-tracking-f54d9',
    storageBucket: 'attendance-tracking-f54d9.appspot.com',
    iosBundleId: 'com.example.attendenceTracking.RunnerTests',
  );
}
